---
title: "analysis_1"
output: 
  html_document:
    code_folding: hide
---

```{r setup, results='hide', warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
# set wd as rproj folder
setwd("../")
# import functions
options(box.path = getwd())
box::use(dplyr[...],
         ggplot2[...],
         lme4[lmer],
         texreg[screenreg, htmlreg],
         plm[plm],
         sandwich[vcovCL, vcovHC],
         lmtest[coeftest],
         lubridate[date],
         magrittr[use_series, extract],
         readr[read_csv],
         # import own project functions
         functions/ts[get_coefs, load_project_data, test_lag])

load_project_data()

my_theme <- theme_minimal() +
  theme(legend.position = "top",
        axis.line.x = element_line(), axis.ticks.x = element_line(),
        plot.caption = element_text(hjust = 0))

theme_set(my_theme)

```


```{r main_plots}
## Main Plots:
# plot of deaths: trusting vs untrusting
data %>% 
  select(location, date, trusting, new_deaths_per_million) %>% 
  na.omit() %>% 
  group_by(trusting, date) %>% 
  summarise(new_deaths_per_million = mean(new_deaths_per_million)) %>% 
  ggplot(aes(date, new_deaths_per_million, colour = factor(trusting))) +
  geom_smooth(span = 0.05, se = FALSE, size = 0.5) +
  # geom_line(alpha = 0.5) +
  scale_x_date(date_breaks = "10 weeks", date_labels = "%b %Y",
               limits = c(date("2020-02-01"), date("2021-03-01"))) +
  scale_y_continuous(limits = c(-0.5, 9)) +
  labs(title = "Daily deaths per million", x = "", y = "", colour = "",
       caption = "Source: Our World in Data") +
  ggsci::scale_color_lancet()

# excess deaths
weekly_data %>% 
  select(location, date, distrust_people, excess_deaths_per_100k) %>% 
  mutate(trusting = ifelse(distrust_people < median(distrust_people), "High trust", "Low trust"),
         excess_per_million = excess_deaths_per_100k * 10) %>% 
  group_by(trusting, date) %>% 
  summarise(excess_deaths = mean(excess_per_million, na.rm = TRUE)) %>% 
  ggplot(aes(date, excess_deaths, colour = factor(trusting))) +
  geom_smooth(span = 0.1, se = FALSE, size = 0.5) +
  # geom_line(alpha = 0.5) +
  scale_x_date(date_breaks = "10 weeks", date_labels = "%b %Y",
               limits = c(date("2020-02-01"), date("2021-03-01"))) +
  scale_y_continuous(limits = c(-0.5, 9)) +
  labs(title = "Estimated excess deaths per million", x = "", y = "", colour = "",
       caption = "Source: Our World in Data") +
  ggsci::scale_color_lancet()

# plot of stringency: 
data %>% 
  select(location, date, trusting, stringency_index) %>% 
  na.omit() %>% 
  group_by(trusting, date) %>% 
  summarise(stringency_index = mean(stringency_index)) %>% 
  ggplot(aes(date, stringency_index, colour = factor(trusting))) +
  geom_smooth(span = 0.01, se = FALSE, size = 0.5) +
  # geom_line() +
  scale_x_date(limits = c(date("2020-01-01"), date("2021-03-01")), 
               date_breaks = "10 weeks", date_labels = "%b %Y") +
  labs(title = "Stringency Index",
       x = "", y = "", colour = "",
       caption = "Source: Our World in Data") +
  ggsci::scale_color_lancet()

# plot of residential
data %>% 
  select(location, date, trusting, res_pct_chng) %>% 
  na.omit() %>%
  group_by(trusting, date) %>% 
  summarise(res_pct_chng = mean(res_pct_chng)) %>% 
  ggplot(aes(date, res_pct_chng, colour = factor(trusting))) +
  geom_smooth(span = 0.1, se = FALSE, size = 0.5) +
  scale_x_date(limits = c(date("2020-03-01"), date("2021-03-01")), 
               date_breaks = "8 weeks", date_labels = "%B") +
  labs(title = "Percent change in residential",
       x = "", y = "", colour = "",
       caption = "Source: Our World in Data") +
  ggsci::scale_color_lancet()

data %>% 
  select(distrust_people, stringency_index, location) %>% 
  na.omit() %>% 
  group_by(location) %>% 
  summarise(distrust_people = mean(distrust_people), 
            stringency_index = mean(stringency_index)) %>% 
  ggplot(aes(distrust_people, stringency_index)) +
  geom_point() +
  geom_smooth(method = lm)

```
  
Main regression models:
Model 1 is a pooled linear regression with location clustered standard errors. All other models use random effects
```{r models, results='asis'}
pooled1 <- data %>% 
  lm(formula = stringency_index ~ distrust_people) %>% 
  coeftest(., vcovCL, cluster = ~location)

model1 <- data %>% 
  lmer(stringency_index ~ distrust_people +
         (1 | location), .)

# adding deaths lag to random effects
model2 <- data %>% 
  lmer(stringency_index ~ distrust_people + deaths_per_mil_lag_7 + 
         (1 | location), .)

# adding res_pct_chng with 28 days of lag
model3 <- data %>% 
  lmer(stringency_index ~ distrust_people + deaths_per_mil_lag_7 + res_chng_lag_34 +
         log(gdp_per_capita) +
         (1 | location), .)

# adding other country fixed variables
model4 <- data %>% 
  lmer(stringency_index ~ distrust_people + res_chng_lag_34 + deaths_per_mil_lag_7 +
         log(gdp_per_capita) + ghs + pop.km2 + democracy_index + ethnic + education_index +
         (1 | location), .)

# add lagged stringency to right hand side of formula
model5 <- data %>% 
  lmer(stringency_index ~ distrust_people + continent + res_chng_lag_34 + deaths_per_mil_lag_7 +
         log(gdp_per_capita) + ghs + pop.km2 + democracy_index + ethnic + education_index +
         (1 | location), .)

htmlreg(list(pooled1, model1, model2, model3, model4, model5), omit.coef = "Intercept")

model4 %>% 
  summary() %>% 
  use_series(coefficients) %>% 
  as_tibble(rownames = "coef", .name_repair = make.names) %>% 
  filter(coef != "(Intercept)") %>% 
  ggplot(aes(Estimate, coef)) +
  geom_point(size = 1) +
  geom_linerange(aes(xmin = Estimate - 1.96 * Std..Error, 
                     xmax = Estimate + 1.96 * Std..Error))




  
```
  
Testing different levels of lag:
```{r lag_test, results='hide'}
lag_df <- data %>% 
  test_lag(stringency_index ~ distrust_people + log(gdp_per_capita) + deaths_per_mil_lag_7 + 
             education_index + ghs + pop.km2 + democracy_index + 
             (1 | location), lag_var = res_pct_chng, n_lag = 50)


lag_df_deaths <- data %>% 
  test_lag(stringency_index ~ distrust_people + log(gdp_per_capita) + res_chng_lag_34 +
             education_index + ghs + pop.km2 + democracy_index + 
             (1 | location), lag_var = new_deaths_per_million, n_lag = 30)

```

```{r coefs_time, results='hide'}
# random effects over time
lmer_time <- data %>% 
  get_coefs(stringency_index ~ distrust_people + res_chng_lag_34 + deaths_per_mil_lag_7 +
              log(gdp_per_capita) + ghs + pop.km2 + democracy_index + ethnic + education_index +
              (1 | location), n_days = 7)

# linear regression over time
lm_time <- data %>% 
  get_coefs(stringency_index ~ distrust_people + res_chng_lag_7 + deaths_per_mil_lag_7 +
              log(gdp_per_capita) + ghs + pop.km2 + democracy_index + ethnic + sch_enrol_per_cap,
            n_days = 1, method = "lm")

```

